# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for Kyro Downloader - Windows EXE.

Uses CustomTkinter for GUI - no runtime binary downloads required.
Everything is bundled in the EXE for reliable distribution.
"""
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

a = Analysis(
    ['src/gui/gui_main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config', 'config'),
    ],
    hiddenimports=[
        # Core
        'src',
        'src.core',
        'src.core.downloader',
        'src.core.download_manager',
        'src.core.queue',
        'src.core.progress',
        'src.core.retry',
        'src.core.concurrent',
        # Services
        'src.services',
        'src.services.archive',
        'src.services.channels',
        'src.services.chapters',
        'src.services.cloud_upload',
        'src.services.compressor',
        'src.services.converter',
        'src.services.cookies_from_browser',
        'src.services.date_filter',
        'src.services.external_dl',
        'src.services.filesize_filter',
        'src.services.format_sorter',
        'src.services.geo_restriction',
        'src.services.impersonation',
        'src.services.info_json',
        'src.services.livestream',
        'src.services.match_filter',
        'src.services.media_server',
        'src.services.metadata',
        'src.services.netrc_auth',
        'src.services.output_template',
        'src.services.scheduler',
        'src.services.search',
        'src.services.sponsorblock',
        'src.services.statistics',
        'src.services.subtitles',
        'src.services.thumbnails',
        'src.services.trimming',
        'src.services.watch_later',
        # Utils
        'src.utils',
        'src.utils.ytdlp_updater',
        'src.utils.app_updater',
        'src.utils.circuit_breaker',
        'src.utils.dedup',
        'src.utils.ffmpeg',
        'src.utils.logger',
        'src.utils.notifications',
        'src.utils.platform',
        'src.utils.url_expander',
        'src.utils.validation',
        # Config
        'src.config',
        'src.config.defaults',
        'src.config.manager',
        'src.config.schema',
        # GUI
        'src.gui',
        'src.gui.app',
        'src.gui.gui_main',
        # CLI commands (imported dynamically)
        'src.cli',
        'src.cli.__main__',
        'src.cli.commands',
        'src.cli.commands.archive',
        'src.cli.commands.channels',
        'src.cli.commands.chapters',
        'src.cli.commands.compress',
        'src.cli.commands.convert',
        'src.cli.commands.external',
        'src.cli.commands.livestream',
        'src.cli.commands.schedule',
        'src.cli.commands.search',
        'src.cli.commands.stats',
        # UI
        'src.ui',
        'src.ui.banner',
        'src.ui.themes',
        'src.ui.tui',
        'src.ui.web',
        'src.ui.web.server',
        'src.ui.web.routes',
        'src.ui.web.websocket',
        # Plugins
        'src.plugins',
        'src.plugins.builtin',
        'src.plugins.builtin.auto_compress',
        'src.plugins.builtin.auto_convert',
        'src.plugins.builtin.auto_organize',
        'src.plugins.builtin.auto_thumbnail',
        'src.plugins.builtin.subtitle_auto',
        # Third-party
        'customtkinter',
        'darkdetect',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.font',
        'tkinter.ttk',
        'yt_dlp',
        'yt_dlp.extractor',
        'yt_dlp.downloader',
        'yt_dlp.postprocessor',
        'rich',
        'rich.console',
        'rich.table',
        'rich.prompt',
        'pydantic',
        'pydantic.fields',
        'yaml',
        'pyfiglet',
        'pyperclip',
        'loguru',
        'plyer',
        'packaging',
        'textual',
        'PIL',
        'requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'numpy',
        'pandas',
        'jupyter',
        'notebook',
        'IPython',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='KyroDownloader',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
