"""Language selector component for Desktop GUI."""

LANGUAGES = {
    "en": {"name": "English", "native": "English"},
    "es": {"name": "Spanish", "native": "Español"},
    "fr": {"name": "French", "native": "Français"},
    "de": {"name": "German", "native": "Deutsch"},
    "it": {"name": "Italian", "native": "Italiano"},
    "pt": {"name": "Portuguese", "native": "Português"},
    "ru": {"name": "Russian", "native": "Русский"},
    "ja": {"name": "Japanese", "native": "日本語"},
    "ko": {"name": "Korean", "native": "한국어"},
    "zh": {"name": "Chinese", "native": "中文"},
    "ar": {"name": "Arabic", "native": "العربية"},
    "hi": {"name": "Hindi", "native": "हिन्दी"},
    "nl": {"name": "Dutch", "native": "Nederlands"},
    "pl": {"name": "Polish", "native": "Polski"},
    "tr": {"name": "Turkish", "native": "Türkçe"},
    "sv": {"name": "Swedish", "native": "Svenska"},
    "da": {"name": "Danish", "native": "Dansk"},
    "fi": {"name": "Finnish", "native": "Suomi"},
    "no": {"name": "Norwegian", "native": "Norsk"},
    "cs": {"name": "Czech", "native": "Čeština"},
    "el": {"name": "Greek", "native": "Ελληνικά"},
    "th": {"name": "Thai", "native": "ไทย"},
    "vi": {"name": "Vietnamese", "native": "Tiếng Việt"},
    "id": {"name": "Indonesian", "native": "Bahasa Indonesia"},
    "uk": {"name": "Ukrainian", "native": "Українська"},
}

TRANSLATIONS = {
    "en": {
        "download": "Download",
        "queue": "Queue",
        "history": "History",
        "search": "Search",
        "statistics": "Statistics",
        "settings": "Settings",
        "url_placeholder": "Paste URL or search query",
        "fetch_info": "Fetch Info",
        "quality": "Quality",
        "format": "Format",
        "audio_format": "Audio",
        "batch_download": "Batch Download",
        "refresh": "Refresh",
        "clear_completed": "Clear Completed",
        "download_queue": "Download Queue",
        "download_history": "Download History",
        "search_placeholder": "Search",
        "platform": "Platform",
        "general_settings": "General Settings",
        "download_settings": "Download Settings",
        "features": "Features",
        "download_path": "Download Path",
        "max_retries": "Max Retries",
        "concurrent_workers": "Concurrent Workers",
        "rate_limit": "Rate Limit",
        "proxy_url": "Proxy URL",
        "desktop_notifications": "Desktop Notifications",
        "auto_update": "Auto-update yt-dlp",
        "check_duplicates": "Check Duplicates",
        "save_settings": "Save Settings",
        "reset_defaults": "Reset to Defaults",
        "language": "Language",
        "open_downloads": "Open Downloads",
        "toggle_theme": "Toggle Theme",
    },
    "es": {
        "download": "Descargar",
        "queue": "Cola",
        "history": "Historial",
        "search": "Buscar",
        "statistics": "Estadísticas",
        "settings": "Configuración",
        "url_placeholder": "Pegar URL o consulta de búsqueda",
        "fetch_info": "Obtener información",
        "quality": "Calidad",
        "format": "Formato",
        "audio_format": "Audio",
        "batch_download": "Descarga por lotes",
        "refresh": "Actualizar",
        "clear_completed": "Limpiar completados",
        "download_queue": "Cola de descarga",
        "download_history": "Historial de descargas",
        "search_placeholder": "Buscar",
        "platform": "Plataforma",
        "general_settings": "Configuración general",
        "download_settings": "Configuración de descarga",
        "features": "Características",
        "download_path": "Ruta de descarga",
        "max_retries": "Reintentos máximos",
        "concurrent_workers": "Trabajadores concurrentes",
        "rate_limit": "Límite de velocidad",
        "proxy_url": "URL del proxy",
        "desktop_notifications": "Notificaciones de escritorio",
        "auto_update": "Actualización automática",
        "check_duplicates": "Verificar duplicados",
        "save_settings": "Guardar configuración",
        "reset_defaults": "Restablecer valores",
        "language": "Idioma",
        "open_downloads": "Abrir descargas",
        "toggle_theme": "Cambiar tema",
    },
    "fr": {
        "download": "Télécharger",
        "queue": "File d'attente",
        "history": "Historique",
        "search": "Rechercher",
        "statistics": "Statistiques",
        "settings": "Paramètres",
        "url_placeholder": "Coller l'URL ou la recherche",
        "fetch_info": "Récupérer les infos",
        "quality": "Qualité",
        "format": "Format",
        "audio_format": "Audio",
        "batch_download": "Téléchargement par lot",
        "refresh": "Actualiser",
        "clear_completed": "Effacer terminés",
        "download_queue": "File de téléchargement",
        "download_history": "Historique des téléchargements",
        "search_placeholder": "Rechercher",
        "platform": "Plateforme",
        "general_settings": "Paramètres généraux",
        "download_settings": "Paramètres de téléchargement",
        "features": "Fonctionnalités",
        "download_path": "Chemin de téléchargement",
        "max_retries": "Tentatives max",
        "concurrent_workers": "Travailleurs simultanés",
        "rate_limit": "Limite de débit",
        "proxy_url": "URL du proxy",
        "desktop_notifications": "Notifications bureau",
        "auto_update": "Mise à jour auto",
        "check_duplicates": "Vérifier les doublons",
        "save_settings": "Sauvegarder",
        "reset_defaults": "Réinitialiser",
        "language": "Langue",
        "open_downloads": "Ouvrir téléchargements",
        "toggle_theme": "Changer le thème",
    },
    "de": {
        "download": "Herunterladen",
        "queue": "Warteschlange",
        "history": "Verlauf",
        "search": "Suche",
        "statistics": "Statistiken",
        "settings": "Einstellungen",
        "url_placeholder": "URL einfügen oder suchen",
        "fetch_info": "Infos abrufen",
        "quality": "Qualität",
        "format": "Format",
        "audio_format": "Audio",
        "batch_download": "Batch-Download",
        "refresh": "Aktualisieren",
        "clear_completed": "Fertige löschen",
        "download_queue": "Download-Warteschlange",
        "download_history": "Download-Verlauf",
        "search_placeholder": "Suche",
        "platform": "Plattform",
        "general_settings": "Allgemeine Einstellungen",
        "download_settings": "Download-Einstellungen",
        "features": "Funktionen",
        "download_path": "Download-Pfad",
        "max_retries": "Max. Wiederholungen",
        "concurrent_workers": "Gleichzeitige Worker",
        "rate_limit": "Ratenbegrenzung",
        "proxy_url": "Proxy-URL",
        "desktop_notifications": "Desktop-Benachrichtigungen",
        "auto_update": "Auto-Update",
        "check_duplicates": "Duplikate prüfen",
        "save_settings": "Einstellungen speichern",
        "reset_defaults": "Zurücksetzen",
        "language": "Sprache",
        "open_downloads": "Downloads öffnen",
        "toggle_theme": "Thema wechseln",
    },
    "it": {
        "download": "Scarica",
        "queue": "Coda",
        "history": "Cronologia",
        "search": "Cerca",
        "statistics": "Statistiche",
        "settings": "Impostazioni",
        "url_placeholder": "Incolla URL o cerca",
        "fetch_info": "Recupera info",
        "quality": "Qualità",
        "format": "Formato",
        "audio_format": "Audio",
        "batch_download": "Download batch",
        "refresh": "Aggiorna",
        "clear_completed": "Cancella completati",
        "download_queue": "Coda di download",
        "download_history": "Cronologia download",
        "search_placeholder": "Cerca",
        "platform": "Piattaforma",
        "general_settings": "Impostazioni generali",
        "download_settings": "Impostazioni download",
        "features": "Funzionalità",
        "download_path": "Percorso download",
        "max_retries": "Tentativi massimi",
        "concurrent_workers": "Worker simultanei",
        "rate_limit": "Limite velocità",
        "proxy_url": "URL proxy",
        "desktop_notifications": "Notifiche desktop",
        "auto_update": "Aggiornamento automatico",
        "check_duplicates": "Controlla duplicati",
        "save_settings": "Salva impostazioni",
        "reset_defaults": "Ripristina predefiniti",
        "language": "Lingua",
        "open_downloads": "Apri download",
        "toggle_theme": "Cambia tema",
    },
    "pt": {
        "download": "Baixar",
        "queue": "Fila",
        "history": "Histórico",
        "search": "Pesquisar",
        "statistics": "Estatísticas",
        "settings": "Configurações",
        "url_placeholder": "Colar URL ou pesquisar",
        "fetch_info": "Obter informações",
        "quality": "Qualidade",
        "format": "Formato",
        "audio_format": "Áudio",
        "batch_download": "Download em lote",
        "refresh": "Atualizar",
        "clear_completed": "Limpar concluídos",
        "download_queue": "Fila de download",
        "download_history": "Histórico de downloads",
        "search_placeholder": "Pesquisar",
        "platform": "Plataforma",
        "general_settings": "Configurações gerais",
        "download_settings": "Configurações de download",
        "features": "Recursos",
        "download_path": "Caminho de download",
        "max_retries": "Máx. tentativas",
        "concurrent_workers": "Workers simultâneos",
        "rate_limit": "Limite de taxa",
        "proxy_url": "URL do proxy",
        "desktop_notifications": "Notificações desktop",
        "auto_update": "Atualização automática",
        "check_duplicates": "Verificar duplicatas",
        "save_settings": "Salvar configurações",
        "reset_defaults": "Redefinir padrões",
        "language": "Idioma",
        "open_downloads": "Abrir downloads",
        "toggle_theme": "Alternar tema",
    },
    "ru": {
        "download": "Скачать",
        "queue": "Очередь",
        "history": "История",
        "search": "Поиск",
        "statistics": "Статистика",
        "settings": "Настройки",
        "url_placeholder": "Вставьте URL или запрос",
        "fetch_info": "Получить информацию",
        "quality": "Качество",
        "format": "Формат",
        "audio_format": "Аудио",
        "batch_download": "Пакетная загрузка",
        "refresh": "Обновить",
        "clear_completed": "Очистить завершённые",
        "download_queue": "Очередь загрузок",
        "download_history": "История загрузок",
        "search_placeholder": "Поиск",
        "platform": "Платформа",
        "general_settings": "Общие настройки",
        "download_settings": "Настройки загрузки",
        "features": "Возможности",
        "download_path": "Путь загрузки",
        "max_retries": "Макс. попыток",
        "concurrent_workers": "Параллельные задачи",
        "rate_limit": "Ограничение скорости",
        "proxy_url": "URL прокси",
        "desktop_notifications": "Уведомления рабочего стола",
        "auto_update": "Автообновление",
        "check_duplicates": "Проверка дубликатов",
        "save_settings": "Сохранить настройки",
        "reset_defaults": "Сбросить по умолчанию",
        "language": "Язык",
        "open_downloads": "Открыть загрузки",
        "toggle_theme": "Переключить тему",
    },
    "ja": {
        "download": "ダウンロード",
        "queue": "キュー",
        "history": "履歴",
        "search": "検索",
        "statistics": "統計",
        "settings": "設定",
        "url_placeholder": "URLを貼り付けるか検索",
        "fetch_info": "情報を取得",
        "quality": "品質",
        "format": "フォーマット",
        "audio_format": "オーディオ",
        "batch_download": "一括ダウンロード",
        "refresh": "更新",
        "clear_completed": "完了をクリア",
        "download_queue": "ダウンロードキュー",
        "download_history": "ダウンロード履歴",
        "search_placeholder": "検索",
        "platform": "プラットフォーム",
        "general_settings": "一般設定",
        "download_settings": "ダウンロード設定",
        "features": "機能",
        "download_path": "ダウンロードパス",
        "max_retries": "最大リトライ数",
        "concurrent_workers": "同時ワーカー数",
        "rate_limit": "レート制限",
        "proxy_url": "プロキシURL",
        "desktop_notifications": "デスクトップ通知",
        "auto_update": "自動更新",
        "check_duplicates": "重複チェック",
        "save_settings": "設定を保存",
        "reset_defaults": "デフォルトに戻す",
        "language": "言語",
        "open_downloads": "ダウンロードを開く",
        "toggle_theme": "テーマ切替",
    },
    "ko": {
        "download": "다운로드",
        "queue": "대기열",
        "history": "기록",
        "search": "검색",
        "statistics": "통계",
        "settings": "설정",
        "url_placeholder": "URL 붙여넣기 또는 검색",
        "fetch_info": "정보 가져오기",
        "quality": "품질",
        "format": "형식",
        "audio_format": "오디오",
        "batch_download": "일괄 다운로드",
        "refresh": "새로고침",
        "clear_completed": "완료 지우기",
        "download_queue": "다운로드 대기열",
        "download_history": "다운로드 기록",
        "search_placeholder": "검색",
        "platform": "플랫폼",
        "general_settings": "일반 설정",
        "download_settings": "다운로드 설정",
        "features": "기능",
        "download_path": "다운로드 경로",
        "max_retries": "최대 재시도",
        "concurrent_workers": "동시 작업자",
        "rate_limit": "속도 제한",
        "proxy_url": "프록시 URL",
        "desktop_notifications": "데스크톱 알림",
        "auto_update": "자동 업데이트",
        "check_duplicates": "중복 확인",
        "save_settings": "설정 저장",
        "reset_defaults": "기본값으로 재설정",
        "language": "언어",
        "open_downloads": "다운로드 열기",
        "toggle_theme": "테마 전환",
    },
    "zh": {
        "download": "下载",
        "queue": "队列",
        "history": "历史",
        "search": "搜索",
        "statistics": "统计",
        "settings": "设置",
        "url_placeholder": "粘贴URL或搜索",
        "fetch_info": "获取信息",
        "quality": "质量",
        "format": "格式",
        "audio_format": "音频",
        "batch_download": "批量下载",
        "refresh": "刷新",
        "clear_completed": "清除已完成",
        "download_queue": "下载队列",
        "download_history": "下载历史",
        "search_placeholder": "搜索",
        "platform": "平台",
        "general_settings": "常规设置",
        "download_settings": "下载设置",
        "features": "功能",
        "download_path": "下载路径",
        "max_retries": "最大重试次数",
        "concurrent_workers": "并发工作线程",
        "rate_limit": "速率限制",
        "proxy_url": "代理URL",
        "desktop_notifications": "桌面通知",
        "auto_update": "自动更新",
        "check_duplicates": "检查重复",
        "save_settings": "保存设置",
        "reset_defaults": "重置为默认",
        "language": "语言",
        "open_downloads": "打开下载",
        "toggle_theme": "切换主题",
    },
    "ar": {
        "download": "تحميل",
        "queue": "قائمة الانتظار",
        "history": "السجل",
        "search": "بحث",
        "statistics": "الإحصائيات",
        "settings": "الإعدادات",
        "url_placeholder": "الصق الرابط أو ابحث",
        "fetch_info": "جلب المعلومات",
        "quality": "الجودة",
        "format": "التنسيق",
        "audio_format": "الصوت",
        "batch_download": "تحميل دفعة",
        "refresh": "تحديث",
        "clear_completed": "مسح المكتملة",
        "download_queue": "قائمة التحميل",
        "download_history": "سجل التحميل",
        "search_placeholder": "بحث",
        "platform": "المنصة",
        "general_settings": "الإعدادات العامة",
        "download_settings": "إعدادات التحميل",
        "features": "الميزات",
        "download_path": "مسار التحميل",
        "max_retries": "الحد الأقصى للمحاولات",
        "concurrent_workers": "العمليات المتزامنة",
        "rate_limit": "حد السرعة",
        "proxy_url": "رابط الوكيل",
        "desktop_notifications": "إشعارات سطح المكتب",
        "auto_update": "التحديث التلقائي",
        "check_duplicates": "فحص التكرارات",
        "save_settings": "حفظ الإعدادات",
        "reset_defaults": "إعادة التعيين",
        "language": "اللغة",
        "open_downloads": "فتح التنزيلات",
        "toggle_theme": "تبديل السمة",
    },
    "hi": {
        "download": "डाउनलोड",
        "queue": "कतार",
        "history": "इतिहास",
        "search": "खोजें",
        "statistics": "आँकड़े",
        "settings": "सेटिंग्स",
        "url_placeholder": "URL पेस्ट करें या खोजें",
        "fetch_info": "जानकारी लाएं",
        "quality": "गुणवत्ता",
        "format": "प्रारूप",
        "audio_format": "ऑडियो",
        "batch_download": "बैच डाउनलोड",
        "refresh": "रीफ़्रेश",
        "clear_completed": "पूर्ण साफ़ करें",
        "download_queue": "डाउनलोड कतार",
        "download_history": "डाउनलोड इतिहास",
        "search_placeholder": "खोजें",
        "platform": "प्लेटफ़ॉर्म",
        "general_settings": "सामान्य सेटिंग्स",
        "download_settings": "डाउनलोड सेटिंग्स",
        "features": "विशेषताएँ",
        "download_path": "डाउनलोड पथ",
        "max_retries": "अधिकतम पुनः प्रयास",
        "concurrent_workers": "समवर्ती वर्कर्स",
        "rate_limit": "दर सीमा",
        "proxy_url": "प्रॉक्सी URL",
        "desktop_notifications": "डेस्कटॉप सूचनाएँ",
        "auto_update": "स्वतः अपडेट",
        "check_duplicates": "डुप्लिकेट जाँचें",
        "save_settings": "सेटिंग्स सहेजें",
        "reset_defaults": "डिफ़ॉल्ट रीसेट",
        "language": "भाषा",
        "open_downloads": "डाउनलोड खोलें",
        "toggle_theme": "थीम बदलें",
    },
    "nl": {
        "download": "Downloaden",
        "queue": "Wachtrij",
        "history": "Geschiedenis",
        "search": "Zoeken",
        "statistics": "Statistieken",
        "settings": "Instellingen",
        "url_placeholder": "URL plakken of zoeken",
        "fetch_info": "Info ophalen",
        "quality": "Kwaliteit",
        "format": "Formaat",
        "audio_format": "Audio",
        "batch_download": "Batch downloaden",
        "refresh": "Vernieuwen",
        "clear_completed": "Voltooide wissen",
        "download_queue": "Downloadwachtrij",
        "download_history": "Downloadgeschiedenis",
        "search_placeholder": "Zoeken",
        "platform": "Platform",
        "general_settings": "Algemene instellingen",
        "download_settings": "Downloadinstellingen",
        "features": "Functies",
        "download_path": "Downloadpad",
        "max_retries": "Max. pogingen",
        "concurrent_workers": "Gelijktijdige workers",
        "rate_limit": "Snelheidslimiet",
        "proxy_url": "Proxy-URL",
        "desktop_notifications": "Desktopmeldingen",
        "auto_update": "Automatisch bijwerken",
        "check_duplicates": "Duplicaten controleren",
        "save_settings": "Instellingen opslaan",
        "reset_defaults": "Standaard herstellen",
        "language": "Taal",
        "open_downloads": "Downloads openen",
        "toggle_theme": "Thema wisselen",
    },
    "pl": {
        "download": "Pobierz",
        "queue": "Kolejka",
        "history": "Historia",
        "search": "Szukaj",
        "statistics": "Statystyki",
        "settings": "Ustawienia",
        "url_placeholder": "Wklej URL lub wyszukaj",
        "fetch_info": "Pobierz informacje",
        "quality": "Jakość",
        "format": "Format",
        "audio_format": "Audio",
        "batch_download": "Pobieranie wsadowe",
        "refresh": "Odśwież",
        "clear_completed": "Wyczyść ukończone",
        "download_queue": "Kolejka pobierania",
        "download_history": "Historia pobierania",
        "search_placeholder": "Szukaj",
        "platform": "Platforma",
        "general_settings": "Ustawienia ogólne",
        "download_settings": "Ustawienia pobierania",
        "features": "Funkcje",
        "download_path": "Ścieżka pobierania",
        "max_retries": "Maks. ponowień",
        "concurrent_workers": "Równoległe zadania",
        "rate_limit": "Limit prędkości",
        "proxy_url": "URL proxy",
        "desktop_notifications": "Powiadomienia pulpitu",
        "auto_update": "Automatyczna aktualizacja",
        "check_duplicates": "Sprawdź duplikaty",
        "save_settings": "Zapisz ustawienia",
        "reset_defaults": "Przywróć domyślne",
        "language": "Język",
        "open_downloads": "Otwórz pobrane",
        "toggle_theme": "Przełącz motyw",
    },
    "tr": {
        "download": "İndir",
        "queue": "Sıra",
        "history": "Geçmiş",
        "search": "Ara",
        "statistics": "İstatistikler",
        "settings": "Ayarlar",
        "url_placeholder": "URL yapıştırın veya arayın",
        "fetch_info": "Bilgi al",
        "quality": "Kalite",
        "format": "Biçim",
        "audio_format": "Ses",
        "batch_download": "Toplu indirme",
        "refresh": "Yenile",
        "clear_completed": "Tamamlananları temizle",
        "download_queue": "İndirme sırası",
        "download_history": "İndirme geçmişi",
        "search_placeholder": "Ara",
        "platform": "Platform",
        "general_settings": "Genel ayarlar",
        "download_settings": "İndirme ayarları",
        "features": "Özellikler",
        "download_path": "İndirme yolu",
        "max_retries": "Maks. deneme",
        "concurrent_workers": "Eşzamanlı işçiler",
        "rate_limit": "Hız sınırı",
        "proxy_url": "Proxy URL",
        "desktop_notifications": "Masaüstü bildirimleri",
        "auto_update": "Otomatik güncelleme",
        "check_duplicates": "Yinelenenleri kontrol et",
        "save_settings": "Ayarları kaydet",
        "reset_defaults": "Varsayılana sıfırla",
        "language": "Dil",
        "open_downloads": "İndirilenleri aç",
        "toggle_theme": "Temayı değiştir",
    },
    "sv": {
        "download": "Ladda ner",
        "queue": "Kö",
        "history": "Historik",
        "search": "Sök",
        "statistics": "Statistik",
        "settings": "Inställningar",
        "url_placeholder": "Klistra in URL eller sök",
        "fetch_info": "Hämta info",
        "quality": "Kvalitet",
        "format": "Format",
        "audio_format": "Ljud",
        "batch_download": "Batch-nerladdning",
        "refresh": "Uppdatera",
        "clear_completed": "Rensa slutförda",
        "download_queue": "Nerladdningskö",
        "download_history": "Nerladdningshistorik",
        "search_placeholder": "Sök",
        "platform": "Plattform",
        "general_settings": "Allmänna inställningar",
        "download_settings": "Nerladdningsinställningar",
        "features": "Funktioner",
        "download_path": "Nerladdningssökväg",
        "max_retries": "Max försök",
        "concurrent_workers": "Samtidiga arbetare",
        "rate_limit": "Hastighetsgräns",
        "proxy_url": "Proxy-URL",
        "desktop_notifications": "Skrivbordsaviseringar",
        "auto_update": "Automatisk uppdatering",
        "check_duplicates": "Kontrollera dubbletter",
        "save_settings": "Spara inställningar",
        "reset_defaults": "Återställ standard",
        "language": "Språk",
        "open_downloads": "Öppna nerladdningar",
        "toggle_theme": "Växla tema",
    },
    "da": {
        "download": "Download",
        "queue": "Kø",
        "history": "Historik",
        "search": "Søg",
        "statistics": "Statistik",
        "settings": "Indstillinger",
        "url_placeholder": "Indsæt URL eller søg",
        "fetch_info": "Hent info",
        "quality": "Kvalitet",
        "format": "Format",
        "audio_format": "Lyd",
        "batch_download": "Batch-download",
        "refresh": "Opdater",
        "clear_completed": "Ryd fuldførte",
        "download_queue": "Downloadkø",
        "download_history": "Downloadhistorik",
        "search_placeholder": "Søg",
        "platform": "Platform",
        "general_settings": "Generelle indstillinger",
        "download_settings": "Downloadindstillinger",
        "features": "Funktioner",
        "download_path": "Downloadsti",
        "max_retries": "Maks. forsøg",
        "concurrent_workers": "Samtidige arbejdere",
        "rate_limit": "Hastighedsgrænse",
        "proxy_url": "Proxy-URL",
        "desktop_notifications": "Skrivebordsnotifikationer",
        "auto_update": "Automatisk opdatering",
        "check_duplicates": "Tjek dubletter",
        "save_settings": "Gem indstillinger",
        "reset_defaults": "Nulstil standard",
        "language": "Sprog",
        "open_downloads": "Åbn downloads",
        "toggle_theme": "Skift tema",
    },
    "fi": {
        "download": "Lataa",
        "queue": "Jono",
        "history": "Historia",
        "search": "Hae",
        "statistics": "Tilastot",
        "settings": "Asetukset",
        "url_placeholder": "Liitä URL tai hae",
        "fetch_info": "Hae tiedot",
        "quality": "Laatu",
        "format": "Muoto",
        "audio_format": "Ääni",
        "batch_download": "Erälataus",
        "refresh": "Päivitä",
        "clear_completed": "Tyhjennä valmiit",
        "download_queue": "Latausjono",
        "download_history": "Lataushistoria",
        "search_placeholder": "Hae",
        "platform": "Alusta",
        "general_settings": "Yleiset asetukset",
        "download_settings": "Latausasetukset",
        "features": "Ominaisuudet",
        "download_path": "Latauspolku",
        "max_retries": "Maks. yritykset",
        "concurrent_workers": "Samanaikaiset työntekijät",
        "rate_limit": "Nopeusrajoitus",
        "proxy_url": "Välityspalvelimen URL",
        "desktop_notifications": "Työpöytäilmoitukset",
        "auto_update": "Automaattinen päivitys",
        "check_duplicates": "Tarkista kaksoiskappaleet",
        "save_settings": "Tallenna asetukset",
        "reset_defaults": "Palauta oletukset",
        "language": "Kieli",
        "open_downloads": "Avaa lataukset",
        "toggle_theme": "Vaihda teemaa",
    },
    "no": {
        "download": "Last ned",
        "queue": "Kø",
        "history": "Historikk",
        "search": "Søk",
        "statistics": "Statistikk",
        "settings": "Innstillinger",
        "url_placeholder": "Lim inn URL eller søk",
        "fetch_info": "Hent info",
        "quality": "Kvalitet",
        "format": "Format",
        "audio_format": "Lyd",
        "batch_download": "Batch-nedlasting",
        "refresh": "Oppdater",
        "clear_completed": "Fjern fullførte",
        "download_queue": "Nedlastingskø",
        "download_history": "Nedlastingshistorikk",
        "search_placeholder": "Søk",
        "platform": "Plattform",
        "general_settings": "Generelle innstillinger",
        "download_settings": "Nedlastingsinnstillinger",
        "features": "Funksjoner",
        "download_path": "Nedlastingssti",
        "max_retries": "Maks. forsøk",
        "concurrent_workers": "Samtidige arbeidere",
        "rate_limit": "Hastighetsgrense",
        "proxy_url": "Proxy-URL",
        "desktop_notifications": "Skrivebordsvarsler",
        "auto_update": "Automatisk oppdatering",
        "check_duplicates": "Sjekk duplikater",
        "save_settings": "Lagre innstillinger",
        "reset_defaults": "Tilbakestill standard",
        "language": "Språk",
        "open_downloads": "Åpne nedlastinger",
        "toggle_theme": "Bytt tema",
    },
    "cs": {
        "download": "Stáhnout",
        "queue": "Fronta",
        "history": "Historie",
        "search": "Hledat",
        "statistics": "Statistiky",
        "settings": "Nastavení",
        "url_placeholder": "Vložte URL nebo hledejte",
        "fetch_info": "Získat informace",
        "quality": "Kvalita",
        "format": "Formát",
        "audio_format": "Zvuk",
        "batch_download": "Dávkové stahování",
        "refresh": "Aktualizovat",
        "clear_completed": "Vymazat dokončené",
        "download_queue": "Fronta stahování",
        "download_history": "Historie stahování",
        "search_placeholder": "Hledat",
        "platform": "Platforma",
        "general_settings": "Obecné nastavení",
        "download_settings": "Nastavení stahování",
        "features": "Funkce",
        "download_path": "Cesta stahování",
        "max_retries": "Max. pokusů",
        "concurrent_workers": "Souběžní pracovníci",
        "rate_limit": "Omezení rychlosti",
        "proxy_url": "URL proxy",
        "desktop_notifications": "Oznámení na ploše",
        "auto_update": "Automatická aktualizace",
        "check_duplicates": "Kontrolovat duplikáty",
        "save_settings": "Uložit nastavení",
        "reset_defaults": "Obnovit výchozí",
        "language": "Jazyk",
        "open_downloads": "Otevřít stahování",
        "toggle_theme": "Přepnout motiv",
    },
    "el": {
        "download": "Λήψη",
        "queue": "Ουρά",
        "history": "Ιστορικό",
        "search": "Αναζήτηση",
        "statistics": "Στατιστικά",
        "settings": "Ρυθμίσεις",
        "url_placeholder": "Επικόλληση URL ή αναζήτηση",
        "fetch_info": "Λήψη πληροφοριών",
        "quality": "Ποιότητα",
        "format": "Μορφή",
        "audio_format": "Ήχος",
        "batch_download": "Ομαδική λήψη",
        "refresh": "Ανανέωση",
        "clear_completed": "Εκκαθάριση ολοκληρωμένων",
        "download_queue": "Ουρά λήψης",
        "download_history": "Ιστορικό λήψεων",
        "search_placeholder": "Αναζήτηση",
        "platform": "Πλατφόρμα",
        "general_settings": "Γενικές ρυθμίσεις",
        "download_settings": "Ρυθμίσεις λήψης",
        "features": "Χαρακτηριστικά",
        "download_path": "Διαδρομή λήψης",
        "max_retries": "Μέγ. επαναλήψεις",
        "concurrent_workers": "Ταυτόχρονοι εργάτες",
        "rate_limit": "Όριο ταχύτητας",
        "proxy_url": "URL διακομιστή μεσολάβησης",
        "desktop_notifications": "Ειδοποιήσεις επιφάνειας εργασίας",
        "auto_update": "Αυτόματη ενημέρωση",
        "check_duplicates": "Έλεγχος διπλοτύπων",
        "save_settings": "Αποθήκευση ρυθμίσεων",
        "reset_defaults": "Επαναφορά προεπιλογών",
        "language": "Γλώσσα",
        "open_downloads": "Άνοιγμα λήψεων",
        "toggle_theme": "Εναλλαγή θέματος",
    },
    "th": {
        "download": "ดาวน์โหลด",
        "queue": "คิว",
        "history": "ประวัติ",
        "search": "ค้นหา",
        "statistics": "สถิติ",
        "settings": "การตั้งค่า",
        "url_placeholder": "วาง URL หรือค้นหา",
        "fetch_info": "ดึงข้อมูล",
        "quality": "คุณภาพ",
        "format": "รูปแบบ",
        "audio_format": "เสียง",
        "batch_download": "ดาวน์โหลดแบบกลุ่ม",
        "refresh": "รีเฟรช",
        "clear_completed": "ล้างรายการที่เสร็จแล้ว",
        "download_queue": "คิวดาวน์โหลด",
        "download_history": "ประวัติการดาวน์โหลด",
        "search_placeholder": "ค้นหา",
        "platform": "แพลตฟอร์ม",
        "general_settings": "การตั้งค่าทั่วไป",
        "download_settings": "การตั้งค่าดาวน์โหลด",
        "features": "คุณสมบัติ",
        "download_path": "เส้นทางการดาวน์โหลด",
        "max_retries": "จำนวนครั้งสูงสุด",
        "concurrent_workers": "ผู้ทำงานพร้อมกัน",
        "rate_limit": "จำกัดอัตรา",
        "proxy_url": "URL พร็อกซี",
        "desktop_notifications": "การแจ้งเตือนบนเดสก์ท็อป",
        "auto_update": "อัปเดตอัตโนมัติ",
        "check_duplicates": "ตรวจสอบรายการซ้ำ",
        "save_settings": "บันทึกการตั้งค่า",
        "reset_defaults": "รีเซ็ตเป็นค่าเริ่มต้น",
        "language": "ภาษา",
        "open_downloads": "เปิดการดาวน์โหลด",
        "toggle_theme": "สลับธีม",
    },
    "vi": {
        "download": "Tải xuống",
        "queue": "Hàng chờ",
        "history": "Lịch sử",
        "search": "Tìm kiếm",
        "statistics": "Thống kê",
        "settings": "Cài đặt",
        "url_placeholder": "Dán URL hoặc tìm kiếm",
        "fetch_info": "Lấy thông tin",
        "quality": "Chất lượng",
        "format": "Định dạng",
        "audio_format": "Âm thanh",
        "batch_download": "Tải hàng loạt",
        "refresh": "Làm mới",
        "clear_completed": "Xóa đã hoàn thành",
        "download_queue": "Hàng chờ tải xuống",
        "download_history": "Lịch sử tải xuống",
        "search_placeholder": "Tìm kiếm",
        "platform": "Nền tảng",
        "general_settings": "Cài đặt chung",
        "download_settings": "Cài đặt tải xuống",
        "features": "Tính năng",
        "download_path": "Đường dẫn tải xuống",
        "max_retries": "Số lần thử tối đa",
        "concurrent_workers": "Tiến trình đồng thời",
        "rate_limit": "Giới hạn tốc độ",
        "proxy_url": "URL proxy",
        "desktop_notifications": "Thông báo máy tính",
        "auto_update": "Tự động cập nhật",
        "check_duplicates": "Kiểm tra trùng lặp",
        "save_settings": "Lưu cài đặt",
        "reset_defaults": "Đặt lại mặc định",
        "language": "Ngôn ngữ",
        "open_downloads": "Mở thư mục tải xuống",
        "toggle_theme": "Đổi giao diện",
    },
    "id": {
        "download": "Unduh",
        "queue": "Antrian",
        "history": "Riwayat",
        "search": "Cari",
        "statistics": "Statistik",
        "settings": "Pengaturan",
        "url_placeholder": "Tempel URL atau cari",
        "fetch_info": "Ambil info",
        "quality": "Kualitas",
        "format": "Format",
        "audio_format": "Audio",
        "batch_download": "Unduh batch",
        "refresh": "Segarkan",
        "clear_completed": "Hapus selesai",
        "download_queue": "Antrian unduhan",
        "download_history": "Riwayat unduhan",
        "search_placeholder": "Cari",
        "platform": "Platform",
        "general_settings": "Pengaturan umum",
        "download_settings": "Pengaturan unduhan",
        "features": "Fitur",
        "download_path": "Jalur unduhan",
        "max_retries": "Maks. percobaan",
        "concurrent_workers": "Pekerja simultan",
        "rate_limit": "Batas kecepatan",
        "proxy_url": "URL proksi",
        "desktop_notifications": "Notifikasi desktop",
        "auto_update": "Pembaruan otomatis",
        "check_duplicates": "Periksa duplikat",
        "save_settings": "Simpan pengaturan",
        "reset_defaults": "Reset ke default",
        "language": "Bahasa",
        "open_downloads": "Buka unduhan",
        "toggle_theme": "Ganti tema",
    },
    "uk": {
        "download": "Завантажити",
        "queue": "Черга",
        "history": "Історія",
        "search": "Пошук",
        "statistics": "Статистика",
        "settings": "Налаштування",
        "url_placeholder": "Вставте URL або пошук",
        "fetch_info": "Отримати інформацію",
        "quality": "Якість",
        "format": "Формат",
        "audio_format": "Аудіо",
        "batch_download": "Пакетне завантаження",
        "refresh": "Оновити",
        "clear_completed": "Очистити завершені",
        "download_queue": "Черга завантажень",
        "download_history": "Історія завантажень",
        "search_placeholder": "Пошук",
        "platform": "Платформа",
        "general_settings": "Загальні налаштування",
        "download_settings": "Налаштування завантаження",
        "features": "Можливості",
        "download_path": "Шлях завантаження",
        "max_retries": "Макс. спроб",
        "concurrent_workers": "Паралельні завдання",
        "rate_limit": "Обмеження швидкості",
        "proxy_url": "URL проксі",
        "desktop_notifications": "Сповіщення робочого столу",
        "auto_update": "Автооновлення",
        "check_duplicates": "Перевірка дублікатів",
        "save_settings": "Зберегти налаштування",
        "reset_defaults": "Скинути за замовчуванням",
        "language": "Мова",
        "open_downloads": "Відкрити завантаження",
        "toggle_theme": "Перемкнути тему",
    },
}


class LanguageSelector:
    def __init__(self, default_lang="en"):
        self._current = default_lang

    @property
    def current(self):
        return self._current

    def set_language(self, code):
        if code in LANGUAGES:
            self._current = code

    def get_language_name(self, code=None):
        c = code or self._current
        lang = LANGUAGES.get(c, {})
        return lang.get("name", c)

    def get_native_name(self, code=None):
        c = code or self._current
        lang = LANGUAGES.get(c, {})
        return lang.get("native", c)

    def get_all_languages(self):
        return LANGUAGES.copy()

    def t(self, key):
        lang_data = TRANSLATIONS.get(self._current, TRANSLATIONS["en"])
        return lang_data.get(key, TRANSLATIONS["en"].get(key, key))
